# Generated by Django 5.1.3 on 2024-11-26 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=200)),
                ("exchange", models.CharField(max_length=200)),
                ("screener", models.CharField(max_length=200)),
                ("interval", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=6, max_digits=15)),
                ("close", models.DecimalField(decimal_places=6, max_digits=15)),
                ("high", models.DecimalField(decimal_places=6, max_digits=15)),
                ("low", models.DecimalField(decimal_places=6, max_digits=15)),
                ("volume", models.DecimalField(decimal_places=6, max_digits=20)),
                ("sma_200", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "daily_macd_line",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                (
                    "daily_macd_signal",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                (
                    "daily_macd_histogram",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                (
                    "weekly_macd_line",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                (
                    "weekly_macd_signal",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                (
                    "weekly_macd_histogram",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                ("rsi", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "stock_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_data",
                        to="StockViewerApp.stock_list",
                    ),
                ),
            ],
        ),
    ]
