# Generated by Django 5.1.3 on 2024-11-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock_list",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
