# Generated by Django 5.1.3 on 2024-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0002_stock_list_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock_list",
            name="interval",
        ),
        migrations.AddField(
            model_name="stock_list",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
