# Generated by Django 5.1.3 on 2024-11-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0003_remove_stock_list_interval_stock_list_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="resistance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="support",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
