# Generated by Django 5.1.3 on 2024-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0004_stockdata_resistance_stockdata_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock_list",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stock_list",
            name="industry",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stock_list",
            name="sector",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
