# Generated by Django 5.1.3 on 2024-11-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0005_stock_list_category_stock_list_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="date",
            field=models.IntegerField(),
        ),
    ]
