# Generated by Django 5.1.3 on 2024-11-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0006_alter_stockdata_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
