# Generated by Django 5.1.3 on 2024-12-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0007_alter_stockdata_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="adx",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="adx_di_negative",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="adx_di_positive",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="awesome_oscillator",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="bollinger_bands_lower",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="bollinger_bands_power",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="bollinger_bands_recommendation",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="bollinger_bands_upper",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="commodity_channel_index",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ema_10",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ema_100",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ema_20",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ema_200",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ema_30",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ema_5",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ema_50",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hull_moving_average",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hull_moving_average_recommendation",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ichimoku_base_line",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ichimoku_recommendation",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="momentum",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="parabolic_sar",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_camarilla_middle",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_camarilla_r1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_camarilla_r2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_camarilla_r3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_camarilla_s1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_camarilla_s2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_camarilla_s3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_classic_middle",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_classic_r1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_classic_r2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_classic_r3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_classic_s1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_classic_s2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_classic_s3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_demark_middle",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_demark_r1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_demark_s1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_fibonacci_middle",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_fibonacci_r1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_fibonacci_r2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_fibonacci_r3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_fibonacci_s1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_fibonacci_s2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_fibonacci_s3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_woodie_middle",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_woodie_r1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_woodie_r2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_woodie_r3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_woodie_s1",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_woodie_s2",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="pivot_woodie_s3",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="price_change",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="recommend_all",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="recommend_ma",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="recommend_other",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="sma_10",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="sma_100",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="sma_20",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="sma_30",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="sma_5",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="sma_50",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="stoch_d",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="stoch_k",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="stoch_rsi",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="stoch_rsi_k",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="two_days_ago_awesome_oscillator",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ultimate_oscillator",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ultimate_oscillator_recommendation",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="volume_weighted_moving_average",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="volume_weighted_moving_average_recommendation",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="williams_r",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="williams_r_recommendation",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_adx_di_negative",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_adx_di_positive",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_awesome_oscillator",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_commodity_channel_index",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_momentum",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_rsi",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_stoch_d",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="yesterday_stoch_k",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="close",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="daily_macd_histogram",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="daily_macd_line",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="daily_macd_signal",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="high",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="low",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="open",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="rsi",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="sma_200",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="volume",
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="weekly_macd_histogram",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="weekly_macd_line",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="weekly_macd_signal",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
    ]
