# Generated by Django 5.1.3 on 2024-12-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockViewerApp", "0008_stockdata_adx_stockdata_adx_di_negative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="current_price",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="daily_macd_score",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="daily_macd_velocity",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="direction",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="ma_score",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="support_resistance_score",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="total_score",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="weekly_macd_score",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="weekly_macd_velocity",
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
    ]
